export const config = {
  VITE_APP_API_KEY: import.meta.env.VITE_APP_API_KEY,
  VITE_APP_AUTHDOMAIN: import.meta.env.VITE_APP_AUTHDOMAIN,
  VITE_APP_PROJECTID: import.meta.env.VITE_APP_PROJECTID,
  VITE_APP_STORAGEBUCKET: import.meta.env.VITE_APP_STORAGEBUCKET,
  VITE_APP_MESSAGINGSENDERID: import.meta.env.VITE_APP_MESSAGINGSENDERID,
  VITE_APP_APPID: import.meta.env.VITE_APP_APPID,
  VITE_APP_MEASUREMENTID: import.meta.env.VITE_APP_MEASUREMENTID,
};
